### ISSUE TITLE
Make current model more automatable

### ISSUE THREAD

**Issue by sam-writer** [CodeForPhilly/chime#101]
> I was hoping to loop over the function in order to generate SIR output (not necessarily markdown, just numerical output) for several different jurisdictions/hospitals 'at once' without having to use the GUI. i mentioned this above and was pointed to models.py, but it doesn't have the super useful extensions available in app.py.  In a thread above, it was recommended to do a fork and dev, but that's a bit beyond me at the moment. Worst case we just run this by hand for all our jurisdictions, but will likely be asked for daily report / simulation testing, so was hoping to automate
> the dataframes that generate the charts would be priority (from which i could compose outcome metrics of interest), and the visuals themselves would not be necessary (but a perk!)
[src](https://codeforphilly.slack.com/archives/CV71EUYD8/p1584642844157700?thread_ts=1584641972.156200&cid=CV71EUYD8)

This is a matter of better encapsulating the modeling code.

**Comment by machow** [comment]
Hey! I told @quinn-dougherty I could quickly refactor some of the app logic to live in a class, that goes essentially from \<parameters currently entangled in UI\> -> a plot

This might also be a good first step for people experimenting with moving away from streamlit, since with this setup, streamlit will essentially just be the view-model

(Taking 30 minutes to do now)

**Comment by quinn-dougherty** [comment]
CLI in https://github.com/CodeForPhilly/chime/pull/170

**Comment by quinn-dougherty** [comment]
i think between recent modularization and the CLI and the scope of this issue, we can close.
