### ISSUE TITLE
Allow a user to save parameter settings

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#146]
Health systems are creating daily reports for multiple hospitals with multiple scenarios.  This can take 1 - 2 hours and when done manually increases the risk of error. 

A user should be able to save their settings so they can share them with others and reuse them later.

**Comment by nickcanz** [comment]
I don't _think_ we're able to do this with the current version of streamlit. There is an open PR on streamlit to add functionality to accomplish this, but it is unmerged: https://github.com/streamlit/streamlit/pull/1169

**Comment by jlubken** [comment]
@Mdraugelis There is a cli that takes a `--file` option to read settings from a file. It doesn't generate png graphs, but it does output csvs.

**Comment by mdbecker** [comment]
Updated the ticket to make it more about the use case and less about the solution. I'm not sure if this changes anything but please take a second look @nickcanz and @jlubken

**Comment by mariekers** [comment]
This might be more feasible once we move off of streamlit - should we wait for that? we can make a plan on how to switchover once the new tool is decided

**Comment by quinn-dougherty** [comment]
should `export settings.cfg` from current state of widgets.

**Comment by pjhoberman** [comment]
Any preference on this being a js or py solution?

**Comment by pjhoberman** [comment]
The branch as pushed does not work, as it has an infinite loop constantly refreshing the charts and overwriting input changes. I need to step away for a bit, but I could use some help. Thanks for everyone who has already chipped in on this issue!

There’s currently an infinite loop that constantly reloads the app, overwriting any changes to the inputs. This happens even if there is not a hash present in the url. I can’t figure out what’s causing it but I figured I’d push this branch in case anyone has bandwidth and ideas. 

As far as the actual issue...

I opted to store the params in the url hash as an easy way for users to save a link, send a link, and open a link without any effort, and thereby see the params as saved. It's not the prettiest solution (it's an ugly URL), but I think it's the easiest method for sharing links. 

There's a button at the bottom of the sidebar:
![image](https://user-images.githubusercontent.com/37924/77857124-e9e15000-71b8-11ea-9555-bf631d550f91.png)

Clicking that button updates the hash with the new params, like so:
`http://0.0.0.0:8050/#market_share=13;susceptible=4119405;known_infected=510;current_hospitalized=14;doubling_time=4;relative_contact_rate=0;hospitalized_rate=2.5;icu_rate=0.75;ventilated_rate=0.5;hospitalized_los=7;icu_los=9;ventilated_los=10;n_days=60;max_y_axis_value=;_as_date-true=on;_show_tables-true=on;_show_tool_details-true=on;_show_additional_projections-true=on;`

and also pops up a confirm dialog to see if the user wants to copy that to their clipboard. I did it this way so that they don't accidentally overwrite their clipboard, though there are more elegant ways to do this.

![image](https://user-images.githubusercontent.com/37924/77857166-2f9e1880-71b9-11ea-80c6-b4de65a42c01.png)

If you want to test this locally, after the page loads you have to stop your server, otherwise the infinite loop overwrites your effort. I'll come back to this tonight / tomorrow, but I am stuck on the infinite loop problem.

I would love feedback on the approach itself from anyone who has it!

**Comment by quinn-dougherty** [comment]
here's PJ's branch https://github.com/CodeForPhilly/chime/tree/146-save-inputs
