### ISSUE TITLE
Integrate settings.cfg to be used by the app

### ISSUE THREAD

**Issue by jlubken** [CodeForPhilly/chime#172]
Consider how settings come from a file and may then be overridden by url query parameters (#146 ).

Rework the defaults.py to incorporate:
- the settings.cfg instead of the settting.py
- maybe move the settings.cfg parser into classmethods of defaults.py
- the bounds validation that is duplicated between the cli argument parser and the ui widgets
- possibly make the Defaults/Constants object own the ranges and help text
- note that (like the settings.py) the rates in the settings file are not the percents in the ui, so the validation help text and messages are different

Some duplication running models with the Parameters object in app.py and cli.py.

And if we want to output png graphs:
- we do need the max_y_axis added as required to the config file, defaults, parameters
- plot to file dependencies without streamlit

**Comment by BrianThomasRoss** [comment]
Currently there are ways of addressing some of the issues through Dash alone so I'm focusing on that right now but one thing to consider is putting the dash app inside a flask app this would allow:

- SQL integration
- authentication (account creation, login, log out)
- true persistence
- Forms
- API integration (remote instances report statistics to central store, applets being used at testing locations to update in real time numbers of confirmed cases)
 - Eventually port to electron making it a cross-platform native desktop application

I think while Dash raises the ceiling significantly on its own, eventually that ceiling will be hit again and making a move to this structure sooner rather than later has significant benefits

**Comment by jlubken** [comment]
@BrianThomasRoss This current issue is not about persistence of user data. Rather, I need a way for the Penn data scientists to update configuration files that represent the defaults for the application. These changes should not be editing code or tied to a code release: thus the settings.cfg instead of settings.py.

Naturally, the config parser could be extended to accept other data or load from a database.
