### ISSUE TITLE
Census should not start from 0

### ISSUE THREAD

**Issue by cjbayesian** [CodeForPhilly/chime#187]
Currently, the census is computed by accumulating a proportion of _new_ cases, and discharging them after 'length of stay'. This does not account for the currently hospitalized cases, as can be seen by this example of setting current hospitalized cases to 4000:
![image](https://user-images.githubusercontent.com/1396669/77251583-850c7f80-6c25-11ea-987f-bb0860838206.png)

The initial model assumed the starting point to be very early on when this had much less impact, however this will be increasingly important for localities that are further along in the course of spread.

**Comment by PhilMiller** [comment]
I'm starting on this. If no one else has done so already and waves me off, I'll try to have a PR posted this evening.

**Comment by PhilMiller** [comment]
Ok, I took time looking at #190 and figuring out testing, so no code tonight, just thoughts.

One way to do this is to treat the input "Currently Hospitalized" as 'hidden' admissions on day 0. Since the chart won't show day 0, but the census will include them in the `cumsum()`, they'll at least be present in the presented count. This is slightly wrong, as a weakened form of the now-invalid very-early-starting-point assumption, since it conflates when they were actually admitted, and doesn't move them with the underlying SIR model values. By starting their stays all at day 0, at least it only over-predicts hospital/icu/vent population.

A more rigorous approach would treat the Infected portion of the population as subpools of outpatient, hosp, icu, and vent, each with their own transition/removal rates.

In the interest of expedience, I'm going to implement the first option.

**Comment by mdbecker** [comment]
Sounds perfect @PhilMiller. We're going to push our a fix to #190 immediately but once you've fixed this we'll push out another release. Thanks!

**Comment by quinn-dougherty** [comment]
was piggybacked into https://github.com/CodeForPhilly/chime/pull/273

**Comment by PhilMiller** [comment]
Yeah, what's left is a single patient difference in #352. Closing this
