### ISSUE TITLE
["bug"] Off-by-one error in either the tooltip or the chart description

### ISSUE THREAD

**Issue by pjhoberman** [CodeForPhilly/chime#239]
### Description:
The dates on the chart tooltips and the dates in the chart description do not match, suggesting there's an off-by-one error in one or both of these. 

### Steps to reproduce:
1. Compare the tooltip on the last data point on the chart to the day/date in the chart description, and notice the dates are different.
2. Extend the chart so that the peak of the curve is visible, and compare the date of the peak of the chart to the description below the chart.

### Expected behavior:
The dates for the peak should match in the tooltip and the description

### What I got instead:
The dates do not match.

![image](https://user-images.githubusercontent.com/37924/77491677-10dc0280-6e04-11ea-9bc3-059cb6988e1a.png)

![image](https://user-images.githubusercontent.com/37924/77491720-2ea96780-6e04-11ea-8855-f49f0a426001.png)

_Note: This has some overlapping code with #237._

**Comment by adibiasio** [comment]
I think I've found the error!

In charts.py, 10 days were automatically subtracted from the plot_projection_days variable in the new_admissions_chart function

![chime_issue](https://user-images.githubusercontent.com/61572112/77698130-7c4ddd80-6f86-11ea-8797-84cbb8dda580.JPG)

Here is what the  locally run version looks like now

![Inkedchime_issue2_LI](https://user-images.githubusercontent.com/61572112/77698568-3d6c5780-6f87-11ea-869b-de4927fbdf82.jpg)

**Comment by adammohammed** [comment]
Same thing exists for the Census chart.
https://github.com/CodeForPhilly/chime/blob/44d9fafebd96166548ded97598be3dce5b106cde/src/penn_chime/charts.py#L65

However, removing that doesn't seem to play well with the Census chart. Notice that the days the peaks occur are dependent on the length of the stay. These could also finish at the "number of days to project" value but it would require running the model with a higher value for `n_days`. This would allow the census chart calculations will be projected out to the target number of days. The If done this way the New Admissions chart would need to truncate the incoming data to the proper amount of days.

![image](https://user-images.githubusercontent.com/12551067/77716132-d31ddc00-6fb3-11ea-8d3b-4268b1bd0884.png)

If the goal is to have all the Census chart lines terminate at the same x-value I think it might be sane to leave this as is. I think at least the New Admissions chart should reach the "number of days to project".

**Comment by adibiasio** [comment]
The "off by one" error now seems to be fixed.

![InkedCHIME_LI](https://user-images.githubusercontent.com/61572112/77836064-35e4b400-7129-11ea-92c0-cd0b601b6e5a.jpg)

Since all of the projections fell one day short, I added one day here.

https://github.com/CodeForPhilly/chime/blob/00d41f3386642f932728532c05390dcdc2ed7fb6/src/penn_chime/presentation.py#L271

I also handled the difference in the chart description in line 157 of charts.py,

![Capture](https://user-images.githubusercontent.com/61572112/77836722-ff119c80-712e-11ea-950b-d2b504bc7f6b.JPG)

All calculations seemed to be the same except for a select few. At 48 and 49 days in the new admissions chart, where the projections of 242 and 228 daily admissions are now 243 and 229 daily admissions. For the census chart, the only difference is at 46 days, where the projection of 1137 is now 1138 people. I am unsure of why these changed and the others remained the same.

(I realize my previously commented concern does not apply, as I misread the chart description)

**Comment by adibiasio** [comment]
With the newly pushed changes, the the if statement in line 157 is no longer needed. The only change is to add one day to `n_days` which is now here,

https://github.com/CodeForPhilly/chime/blob/842e6b316be031e0997b02508311af2cf6312fed/src/penn_chime/presentation.py#L279

`n_days = n_days_input() + 1`

![Screenshot (2)_LI](https://user-images.githubusercontent.com/61572112/77866203-11a7d680-7200-11ea-941f-f3b423197eee.jpg)

The current version stops at May 27th, which is still 59 days from today (March 29th), the addition of 1 day makes the graph end at May 28th, the correct number of projected days. It seems that the census graph disposition lines still end at different days, but this has been brought up in another issue (#350)

Additionally, none of the data seems to have changed anymore.

**Comment by PhilMiller** [comment]
This is actually a kinda horrific first-issue, it turns out. I've dug in and done some research, and it's a result of timezone confusion. If you zoom the chart in to the point where you get a grid line per day, you'll likely see (anywhere other than Dublin time) that the points don't line up with the grid. Or or the other of the tooltip and the dataframe values are going through conversions between UTC and local time
![Screen Shot 2020-04-03 at 9 34 11 PM](https://user-images.githubusercontent.com/126464/78415913-d270ef80-761c-11ea-97e3-01ab3c00bec8.png)
That's what I get in New York, with hours added to the X axis labels to elucidate things.

**Comment by pjhoberman** [comment]
Oh man, sorry for marking it good first issue. I think the original issue was just a weirdness with counting, but as the codebase has evolved it's gotten way more complicated. Sorry!

**Comment by PhilMiller** [comment]
Oh, that's not a problem for me - I've been deep in the guts of the model for the last week. This was just bothering me, so I figured I'd take a look on the off chance it was simple.

I'm not going to try to resolve that discrepancy, now that I've figured out what it is. Someone more comfortable with Python, Numpy, Pandas, and Altair charts, and their data semantics, should knock this down.

**Comment by PhilMiller** [comment]
Just a little more detail, so others don't need to re-derive this conclusion: the axis seems to be living in UTC, given that as modified, it prints no offset. The plotted values and hence the tooltips seem to be getting a conversion to local time applied.
