### ISSUE TITLE
Handle 'mid-growth stage' ["model"]

### ISSUE THREAD

**Issue by cjbayesian** [CodeForPhilly/chime#255]
### Summary
The model was built in the context of the first few days of local outbreak. It is not well equipped to handle projections when there is a non-small number of current infections. There needs to be a way for the user/analyst to specify not only how many cases are currently hospitalized, but also how long it has been since the first case was hospitalized.  In keeping with the goals of the application being as simple as possible while providing actionable projections in terms of hospital-level resource demands, the handling of 'mid-stage' starting points should be kept likewise simple.

### Additional details

After the first week or so of spread, there is additional information contained in the combination of current hospitalized case counts and the number of days since the first case. These two quantities should be combined to provide an estimate of local doubling-time. 

### Suggested fix

- Add an input for 'Days since first hospitalized COVID-19 case' {t_{firstcase}}.
- Start SIR sim from that many days back
- Run argmin_{doublingtime} [abs(hospitalized census - predicted)] at time 0 + t_{fistcase}

**Comment by PhilMiller** [comment]
#257 provides an alternative potential solution

**Comment by PhilMiller** [comment]
It makes a present-day estimate of doubling time, rather than fitting to a history-based estimate.

**Comment by cjbayesian** [comment]
@PhilMiller Can you take a look at my notebook in branch `fithxdoublingtime`?

**Comment by PhilMiller** [comment]
@cjbayesian I just read through it. It seems to be sound.

From a user-oriented perspective, I'm still uncomfortable with asking for a doubling time parameter, since it's one that they'll either need to tediously try to compute, or guess. How about asking for total admissions to date, rather than current in-patients, and when total admissions had been half that?

**Comment by PhilMiller** [comment]
In general, current hospitalizations is kinda a finicky parameter to work with, because it doesn't reflect that some people may have died or been discharged. Early-stage, assuming those were zero seems to be pretty reasonable. Mid-stage, that's harder.

**Comment by cjbayesian** [comment]
Agreed. The idea here is to no longer ask the user to input a doubling time and instead compute it for them using the date of the first hospitalization and the # currently hospitalized (accounting for discharges since we're fitting to the back-casted census projection). The approach could easily be adapted to take cumulative total hospitalizations instead of current. 

Also of note: All of this will of course only work while demand for hospitalizations can actually be met by supply.

**Comment by PhilMiller** [comment]
Ah, right, I missed that "days since (/ date of) first hospitalization" takes the place of doubling time as an input entirely. So, the number of inputs the model asks for stays the same, and a user-estimated parameter is replaced with user-provided data.

On that note, since we each have proposals for data inputs that would let us do parameter estimation, besides back-testing against data from further-advanced regions, would it make sense to display forecasts from the different possible estimated parameters, giving a sense of the uncertainty, and of which way they're trending?

**Comment by cjbayesian** [comment]
Ya totally. I've been encouraged (modeling-wise, not pandemic-wise) that this method results in an estimated 4-day doubling time to date using Penn downtown hospitals as inputs (n_days_since_first_hospitalized = 16, current_hospitalized = 15).  This leads to very similar projections to what we're producing in the app now.

**Comment by PhilMiller** [comment]
How do the forecast values on the negative days match up with observations?

**Comment by cjbayesian** [comment]
@Mdraugelis is working on lining this up and evaluating now.

**Comment by cjbayesian** [comment]
I added in the back-casing comparisons for Penn's downtown hospitals. See https://github.com/CodeForPhilly/chime/blob/fithxdoublingtime/notebooks/Fit%20doubling%20time%20using%20time%20since%20first%20hospitalization.ipynb

**Comment by cjbayesian** [comment]
@PhilMiller Do you want to take a crack at implementing this?

**Comment by quinn-dougherty** [comment]
the basic idea of using minimization of loss between expected hospitalization given a doubling_time and actual hospitalization seems sound to me mathematically, but i'm so new to hospitals my opinion shouldn't matter. 

code-wise, 
1. i think brute force argmin is fine. 
2. wrap cells 60 and 61 in functions and put them in SimSirModel obj
3. use the function based on cell 60 to update state of `self.p.doubling_time` while inside SimSirModel. 

however: 
- question: we need to give the user a choice of inputs because not everybody is going to know the days since first hospitalized. this conditional could make the code a little messy. not intractable but it's worth giving thought to the _best_ way to do this independent of dash vs. streamlit. 
- if we have some messy solution, its possible that it'll make switch to dash more difficult. 
- **so maybe we should focus on making this a CLI feature first, aiming to make it a FE feature second**. 
- if you're dead set on having it in prod monday we can try to work with that.

**Comment by cjbayesian** [comment]
I think that this is becoming increasingly relevant to most users since this also fixes the issue of accounting for current hospitalizations in the census projections. 

Ideally we would like to give the user the ability to either define the doubling time themselves *or* infer it from time since first hospitalization, but we may be able to get around that by computing and presenting the user with the equivalent doubling time for a few 'time since first hospitalization's

**Comment by cjbayesian** [comment]
^ to accomplish the latter, you'd just need to also run another optimization just like the one I outlined, except this one would hold doubling time fixed and loop over `n_days_since_first_hospitalized`.

**Comment by PhilMiller** [comment]
On input UX design: probably preferable to ask for 'date of first admission' than 'days since first admission', since there's an issue to save parameters for users, and the date won't change, while the day count will: #146

**Comment by ckoerber** [comment]
I have added a [notebook](https://github.com/ckoerber/chime/blob/fithxdoublingtime/notebooks/Bayesian%20fit%20of%20SIR%20parameters.ipynb) which follows the idea of fitting hospital data but runs the fit in a Bayesian context (hope I am not too late). This also allows estimating other parameters like `gamma` and initially infected people `I`. 

![bayesian-vs-bruteforce-fit](https://user-images.githubusercontent.com/35035055/77753336-9096e680-7029-11ea-87a4-30512cdf8a8a.png)

Details are in the notebook in the Bayesian section.

In short, I find that the current hospital data might not be constraining enough to disentangle the effects of `I` and `doubling_time` which does affect predictions compared to the current approach. I am not sure what a critical difference is so it might be helpful if someone else takes a look over this.

To do this study, I had to estimate a probability distributions for hospital data (binomial, thanks @cjbayesian for the hint). There is a crucial approximation about how many infected people are being hospitalized in general (I chose p=20% because of symptoms). I do not consider temporal evolution of this number and correlations between hospital data is not present yet (estimated covariance is diagonal). 

Please let me know if you need more details.

**Comment by PhilMiller** [comment]
I've started pushing anywhere I can to publish time series data of hospitalizations/admissions, so we can start to make these fits more reliably. Unfortunately, I'm a complete outsider, so I have no real access to people who can make that happen.

**Comment by misken** [comment]
I will ask the folks at the health system we are working with if they might be willing to share number of admits by date and perhaps % requiring ICU and % vent.

**Comment by fedhere** [comment]
The [notebook](https://github.com/ckoerber/chime/blob/fithxdoublingtime/notebooks/Bayesian%20fit%20of%20SIR%20parameters.ipynb)  is great @ckoerber , and we are doing something similar here (Delaware) but I am wondering what should be fitted:
1) as other pointed out: you can either fit on census or on admits. If you are working with a hospital I would recommend fitting on census but if you are an outsider that wants to get publicly available data you are more likely to find admits data. 

2) the notebook fits for 
- doubling time :  definitely hard to measure so good idea to fit it
- current infected 
- recovered and
- gamma

all hard and medical relevant to know but I think the hospitals are more interested in optimizing ovcer the quantities that are relevant for their hospital and that they can change:
- hospitalization rate
- relative contact rate

when I do fit for those I find that the fit improves a lot if i can add length of stay. 
A more general point is that I find that the data is a lot less well behaved that one might assume, and the fit much more poor. So I worry about people using the result of a fit that has huge uncertainties without understanding the uncertainties (I am fitting in an MCMC framework and the likelihood for the data I have are extremely flat and/or ill-behaved) 


 also unfortunately I am positive the hospitals I am working with are not willing to share those number publicly, other than the admits.
