### ISSUE TITLE
["bug"] Cypress and Kubernetes config use hardcoded port

### ISSUE THREAD

**Issue by ecsmyth** [CodeForPhilly/chime#282]
# Description:
`docker-compose.yml`, Cypress integration tests, and Kubernetes `app.yaml` use a hardcoded port of 8000. These may fail if a non-default port is specified in `.streamlit/config.toml`

### Steps to reproduce:
1. Run `./script/server`
2. Navigate to `http://localhost:8000` in a browser and verify CHIME is running
3. In ./streamlit/config.toml` change port from default `8000` to `8888`
4. Run `./script/update`
5. Refresh the browser page

### Expected behavior:
Browser navigates to CHIME as expected

### What I got instead:
App in container isn't listening on the port specified in `docker-compose.yml` so nothing is served.

**Comment by themightychris** [comment]
I could see a case for cypress being able to run against non-standard ports so that a dev who has to run the app on another port can still run cypress tests. The Cypress case could be improved by having cypress visit `/` instead of the full URL, and then the default baseUrl can be put in `cypress.json`, and then someone running on a nonstandard port could export `CYPRESS_BASE_URL` to override it

I don't see why this matters for the kubernetes setup though or what you'd reasonable change to improve the situation, except maybe have the kubernetes manifest include the same port hardcoded into the `STREAMLIT_SERVER_PORT` env variable to ensure it doesn't matter if someone changes the default in `.streamlit/config.toml` and merged it into a release without updating `Dockerfile` and `app.yaml`... seems far-fetched and there's no blanket solution

**Comment by rcknplyr** [comment]
Issue was opened a while back. Not sure this is impacting users as expected. Closing for now.
