### ISSUE TITLE
Add tests for the cli

### ISSUE THREAD

**Issue by jlubken** [CodeForPhilly/chime#358]
The app gets out of sync with the cli. Few to no test fail when this happens. Add unit tests for the cli.

**Comment by unterwegerK** [comment]
Hi there! As written in Slack, I can have a look on this issue to provide unit tests for the CLI. If that's ok, can you just assign me the issue?

**Comment by PhilMiller** [comment]
Take a crack at it and submit a Pull Request. I'll be happy to help out and check your work.

**Comment by unterwegerK** [comment]
Ok, thanks! One question, just to clarify: "getting out of sync" probably means that calling the SimSirModel from the CLI breaks because parameter and behaviour of the model changes, right? Then I can design the tests accordingly.

**Comment by PhilMiller** [comment]
That was the concern when this issue was opened, yeah. It looks like now, between changes Jason and I made, the set of parameters it parses, and default values, and so forth, is automatically drawn from the same mappings in `parameters.py` that the web interfaces use. 

It would potentially still be worthwhile to have a test that sets up an environment and/or a command line, then calls `cli.main`, generates the expected csv files.
