### ISSUE TITLE
["bug"] current_hospitalized does not match day zero after fitting

### ISSUE THREAD

**Issue by chrisamos52** [CodeForPhilly/chime#504]
### Description:
There is still a major problem with CHIME.  No matter what values you insert for number of patients hospitalized the software does not use the current value but restimates the number at day '0' to be some arbitrary number (always seems to be far less than actual number). The number inputted has to approximately equal the number at day 0 for the software to make any sense
### Steps to reproduce:
1.
2.
3.

### What I got instead:
(screenshots if applicable)

**Comment by misken** [comment]
Just an end user here, but I'm running from command line with following params and I'm getting projected census of 935 on 2020-04-05 as expected:

    --population 5026226
    --market-share 0.32
    --current-hospitalized 935
    --date-first-hospitalized 2020-02-20
    --mitigation-date 2020-03-21
    --current-date 2020-04-05
    --relative-contact-rate 0.30
    --hospitalized-rate 0.025
    --icu-rate 0.0075
    --ventilated-rate 0.005
    --infectious-days 14
    --hospitalized-day 7
    --icu-days 9
    --ventilated-day 10
    --n-days 120

**Comment by PhilMiller** [comment]
Are you providing inputs of doubling time, or date of first hospital admission? In either case, CHIME does a curve fit to estimate the other against current hospitalizations, and then aligns the day with the closest pre-peak census to your parameter as day 0.

Since it sounds like this is providing poor results, please give us the full set of inputs you're providing, so we can investigate. Text, screenshots, whatever, but we need the details.

Also, are you using the web app at https://penn-chime.phl.io/ or some local installation? If local, what git commit do you have?

**Comment by jlubken** [comment]
This may have been fixed with #519
