### ISSUE TITLE
Current Hospitalized/Date First Hospitalized combination bug

### ISSUE THREAD

**Issue by solidmadrid** [CodeForPhilly/chime#555]
There seems to be an issue with a parameter combination. The app works correctly if I put anything less than 4 current hospitalized patients, but as soon as I try to put in a "Date First Hospitalized" value, the app crashes and shows this below error.
![image](https://user-images.githubusercontent.com/12716657/79371161-e8868600-7f21-11ea-9754-9306afb2aab1.png)

**Comment by PhilMiller** [comment]
So, the issue is that the parameters as entered imply an effective pre-mitigation doubling time of greater than 15 days. The code should trap this and say that it seems unreasonable.

If you're actually trying to get a forecast, try changing the inputs in a different order, since it's updating after the change to each one.

Even if an error does appear, changing subsequent parameters will keep re-running the forecast with the new inputs, so this should not be a bar to usage.
