### ISSUE TITLE
unable to connect heroku app to frontend router via new toml files.

### ISSUE THREAD

**Issue by MooseQuest** [CodeForPhilly/chime#64]
Problem: When launching the heroku app without the setup.sh, H11's appear (router backlog) because the app is not being connected on the backend.

Solution: Re add the setup.sh allowing the $PORT to determine the port for the .toml files for streamlit.

**Comment by themightychris** [comment]
ohh is that the issue and why $PORT exists? because heroku needs to dynamically inject a port number for the app to listen on?

If that's the case, we should still be able to get rid of setup.sh in favor of the versioned `.streamlit/*.toml` files, and use the `STREAMLIT_SERVER_PORT` environment variable instead to override port at runtime

See https://codeforphilly.github.io/chime/contributing/app-dev.html#choosing-a-different-port

**Comment by themightychris** [comment]
I think procfile could just be:

```Procfile
web: STREAMLIT_SERVER_PORT=$PORT streamlit run app.py
```

**Comment by MooseQuest** [comment]
Yes -- Essentially the app comes up on a random port and the router connects to it. If you do interactive session with your app you can cat the environment variables. Usually there is a helper file that goes along with heroku apps that sets those up so when the app launches it configures itself. It's a good principal for docker images too.
